[project]
name = "boxworld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.3",
    "onnx>=1.20.1",
    "onnxruntime>=1.24.1",
    "stable-baselines3>=2.7.1",
    "torch>=2.10.0",
]
